2-FavoritePhoto-2/2-FavoritePhoto-2-FE

components/Common/Dropdown/Sort/Attribute.js, components/Common/Dropdown/Sort/Rating.js, components/Common/Dropdown/Sort/Soldout.js, components/Common/Dropdown/Sort/Sort.js, components/Common/Dropdown/Sort/Sort.module.css, components/Common/Modal/Notification.js, components/Common/Modal/Notification.module.css, pages/index.js
components/Common/Modal/
- Notification.js
-  Notification.module.css
- type별로 알림 모달 다르게 객체 선언
- data는 부모 컴포넌트에서 받아서 설명으로 내려줌
- onButtonClick 역시 부모 컴포넌트에서 실행하는 작업 필요
- 미디어쿼리 완성
=> [양가현] Feat/알림 모달

components/Common/Dropdown/Sort/Attribute.js, components/Common/Dropdown/Sort/Rating.js, components/Common/Dropdown/Sort/Soldout.js, components/Common/Dropdown/Sort/Sort.js, components/Common/Dropdown/Sort/Sort.module.css, pages/index.js
components/Common/Dropdown/
- Attribute.js
- Rating.js
- Soldout.js
- Sort.js
- Sort.module.css
- ALL 리스트 전체 삭제
새로고침으로 전체 목록 보여주는 부분은 부모 컴포넌트에서 useState 이용해서 전체 초기화로 진행해야 할 것 같습니다.
=> [양가현] Feat/dropdown

components/Common/Dropdown/Sort/Attribute.js, components/Common/Dropdown/Sort/Sort.module.css, pages/index.js
- Attribute.js
- Sort.module.css
- 포켓몬 타입별 속성 추가
- 스크롤바 추가
=> [양가현] Feat/드롭다운

components/Common/SuccessFail/SuccessFail.js, components/Common/SuccessFail/SuccessFail.module.css, pages/index.js
- SuccessFail.js
- SuccessFail.module.css
- 타입별 성공, 실패 모달 구현
- 미디어쿼리 완성
=> [양가현] Feat/성공 실패 모달

components/Common/SuccessFail/SuccessFail.js, components/Common/SuccessFail/SuccessFail.module.css, pages/index.js, styles/globals.css
=> [양가현] Feat/여백 세팅

components/Common/Modal/CardEdit.js, components/Common/Modal/CardEdit.module.css
- CardEdit.js / css
- - [x] 수정 모달 UI 구현
- 판매 모달과 똑같은 UI 이기 때문에 제목과 버튼 이름 정도만 수정하였습니다.
=> [서유림] Feat: 수정 모달 UI 구현

pages/myGallery/[id]/index.js, styles/MyGalleryDetail.module.css
- myGallery > [id] > index.js / css
- - [x] 마이갤러리 상세 페이지 UI
- - [x] 마이갤러리 상세 페이지 미디어 쿼리
- 세부 정보 카드 컴포넌트 구현된 후 수정할 예정입니다.
=> [서유림] Feat: 상세페이지 UI 구현

components/Common/Dropdown/Sort/Attribute.js, components/Common/Modal/MultiFilter.js, components/Common/Modal/MultiFilter.module.css, components/PocketPlace/PocketPlaceFilter.js
- MultiFilter.js
- MultiFilter.module.css
- 미디어쿼리 모바일용 정렬 추가
- props로 정렬 속성 집합
---
사용하실 props를 선택해주세요
<MultiFilterModal filterKeys={["등급", "속성", "매진여부"]} />
=> [양가현] Feat: 모바일용 정렬 모달

components/Common/Dropdown/Sort/Sort.module.css, components/Common/Modal/MultiFilter.module.css, components/Common/SearchBar/SearchBar.module.css, components/PocketPlace/PocketPlaceFilter.js, components/PocketPlace/PocketPlaceFilter.module.css, components/PocketPlace/PocketPlaceTitle.js, components/PocketPlace/PocketPlaceTitle.module.css
- Sort.module.css
- MultiFilter.module.css
- SearchBar.module.css
- PocketPlaceFilter.js
- PocketPlaceFilter.module.css
- PocketPlaceTitle.js
- PocketPlaceTitle.module.css
- 검색바와 정렬 드롭박스 페이지마다 크기 적용할 수 있도록 100%로 변경
- MultiFilter 크기 고정
- 포켓플레이스 모바일 미디어 쿼리 적용
- 드롭박스 초기화용 새로고침 이미지 추가
---
카드 사이에 공백이 너무 큰 것 같기도 합니다....
---
https://github.com/user-attachments/assets/20337104-4039-4aeb-a972-bc102387008d
=> [양가현] Feat: 포켓플레이스 모바일

components/Common/CardInfo/CardSellInfo.js, components/Common/CardInfo/CardSellInfo.module.css, components/Common/CardInfo/MyCardDetail.js, components/Common/CardInfo/MyCardDetail.module.css, components/Common/Input/Input.module.css, components/Common/Modal/CardEdit.js, components/Common/Modal/CardSell.js, pages/index.js
- CardSellInfo.js / css
- MyCardDetail.js / css
- - [x] 카드 판매 세부정보 컴포넌트 구현
- - [x] 내 카드 상세 정보 컴포넌트 구현
- - [x] 미디어쿼리 작성 완료
- Input.css
- CardEdit.js
- CardSell.js
- - [x] input 너비 조정
- - [x] 속성 기타 -> 노말로 변경
=> [서유림] Feat: 내카드 세부정보

components/Common/Input/Dropdown.module.css, components/Common/Input/Input.js, components/Common/Input/Input.module.css, components/CreateCard/CreateForm.js, components/CreateCard/CreateForm.module.css, components/CreateCard/CreateTitle.js, components/CreateCard/CreateTitle.module.css, pages/index.js, pages/myGallery/create.js, styles/CreateCard.module.css
- myGallery > create.js / css
- CreateTitle.js / css
- CreateForm.js / css
- - [x] 포토 카드 생성 페이지 UI 구현
- - [x] 미디어쿼리 작성
- Dropdown.js / css
- Input.js /css
- - [x] 너비 조정
=> [서유림] Feat: 포토카드생성 페이지UI

components/Common/Quantity/QuantityCard.module.css, components/Common/Quantity/QuantityCard_buyer.js, components/Common/Quantity/QuantityCard_seller.js, pages/card/[id]/index.js
추가한 파일
QuantityCard_buyer.js
QuantityCard_seller.js
QuantityCard.module.css
수정한 목록
수량 카드 - 구매자 / 판매자 구현
api 만들게 되면 등급에따른 색변화 구현예정,
=> [방신철] Feat: 수량카드-구매자/판매자 구현

components/Common/Modal/Exchange.js, components/Common/Modal/Exchange.module.css, hooks/contexts/UserContext.js, pages/_app.js, pages/card/[id]/index.js, pages/index.js, styles/cardDetail.module.css
card/
[id]/
index.js /css 파일수정
common/
modal/
Exchange.js /css
hooks/
context/
UserContext.js 파일 추가
현재 목데이터 미구현으로 api는 주석처리함. 
api 관련 코드는 mock데이터 구현하게되면 추가 구현할 예정
판매자 , 구매자 의 데이터를 받아옴에 따라 UI변경되도록 상태값 추가.
api 만들게 되면 추가 구현할 예정.
Exchange 모달 CSS 추가 /수정
모바일 css 추가(멀티필터추가)
태블릿 css 수정
=> [방신철]Feat/상세페이지 판매자,구매자구별

components/Common/Modal/Exchange.js, components/Common/Modal/Exchange.module.css, components/Common/Modal/Notification.js, components/Common/Quantity/QuantityCard_buyer.js, hooks/contexts/UserContext.js, pages/_app.js, pages/card/[id]/index.js, pages/index.js, styles/cardDetail.module.css
수정한 파일
Notification.js 에 프롭스 추가
common/
quantityCardBuyer에 notification 추가
card/
[id]/
index.js 에 교환 제시목록 추가
=> [방신철]Feat/구매하기모달적용,제시교환목록

components/Common/Grade/Grade.module.css, components/PocketPlace/PocketPlaceList.js, components/PocketPlace/PocketPlaceTitle.js, next.config.mjs, package-lock.json, package.json, pages/pocket_place/index.js, public/mockData.json
- PocketPlaceTitle.js
- next.config.mjs
- package.json
- pocket_place/index.js
- List.js에서 무한 스크롤링 코드를 추가하였습니다.
- Title.js에서 나의 포토카드 판매하기를 누르면 리스트 모달이 뜨도록 변경하였습니다.
- next.config.mjs에서 Image/next를 쓸 때 외부 이미지 문제로 unoptimized 하도록 하였습니다.
-  package.json에서 무한 스크롤링을 위한 lodash 패키지를 추가하였습니다.
- index.js에서 오타를 수정하였습니다.
---
실제 api 반영 후 안될 수도 있지만, 목데이터 결과는 완성했습니다. 추후에 문제가 생길 시 수정하도록 하겠습니다.
+ 로딩 이미지 추가도 고려 중
---
https://github.com/user-attachments/assets/2bed097c-9005-46e5-ac19-cc9409f4164c
=> [양가현] Feat: 포켓플레이스 페이지 무한스크롤링

components/Common/PhotoCard/PhotoCard.module.css
=> [서유림] fix: 포토카드 사진 너비 조정

pages/auth/login.js, pages/auth/signup.js, styles/Login.module.css, styles/Signup.module.css
수정한 파일
* pages/auth/login.js
* pages/auth/signup.js
* styles/Signup.module.css
* styles/Login.module.css
css 부분을 수정을 해야합니다.
수정 후 업데이트 하겠습니다 ...
=> [김윤서] Feat: 로그인페이지와 회원가입페이지

components/Common/PhotoCard/PhotoCard.module.css
- PhotoCard.module.css
- -[x] 포토카드 css 수정
- 제발 되기를 ..
=> [서유림] Fix: 포토카드 css 수정

components/Common/PhotoCard/PhotoCard.js, components/Common/PhotoCard/PhotoCard.module.css
- PhotoCard.js / css
- - [x] 포토카드 수정 완료
- 제가 테스트 해보았습니다 ! 적용 되는 것 같습니다 !!
=> [서유림] Fix: 포토카드 수정

components/Common/PhotoCard/PhotoCard.js, components/Common/PhotoCard/PhotoCardExchange.js
- PhotoCard.js
- PhotoCardExchange.js
- - [x] 데이터 수정
=> [서유림] Fix: 포토카드 데이터 수정

components/Common/SearchBar/SearchBar.js, components/PocketPlace/PocketPlaceFilter.js, components/PocketPlace/PocketPlaceList.js, components/PocketPlace/PocketPlaceList.module.css
- SearchBar.js
- PocketPlaceList.module.css
- SearchBar.js : 엔터키를 쳤을 때도 검색 가능, 빈칸일 때 전체 목록 보여주기 위한 value= "" 추가
- PocketPlaceList.js : 검색과 필터링 useEffect로 묶음,
- PocketPlaceList.module.css: 포토카드 갭 차이 완화
=> [양가현] Feat: 포켓플레이스 판매

lib/api/auth.js, lib/gnb/gnb.js, lib/gnb/gnb.module.css, pages/_app.js, pages/auth/login.js, pages/auth/signup.js, styles/Login.module.css, styles/Signup.module.css
추가한 파일
* lib/api/auth.js
수정한 파일
* pages/auth/login.js
* pages/auth/signup.js
* styles/Login.module.css
* styles/Signup.module.css
css 수정했습니다
로그인 성공 시 -> 포켓플레이스로 이동
회원가입 성공시 -> 로그인 페이지로 이동으로 변경하였습니다!
=> [김윤서] feat:로그인 회원가입 페이지 수정 및 api연결

components/Common/Modal/CardSell.module.css, components/Common/Modal/Modal.module.css, components/Common/Modal/MultiFilter.js, components/PocketPlace/PocketPlaceList.js, components/PocketPlace/PocketPlaceTitle.js, lib/gnb/gnb.js, pages/_app.js, styles/globals.css
- PocketPlaceTitle.js
- MultiFilter.js
- _app.js
- globals.css
- 엑세스토큰이 있다면, 로그인 notification 이 뜨도록 했습니다. 
- 제가 어디서 얻어온 지 모르는 엑세스토큰으로 확인했을 때, 나의 판매 모달도 잘 뜨는 걸 확인했습니다.
- 멀티필터 alt 추가
- body 위아래 마진 추가
https://github.com/user-attachments/assets/fd260fd8-17f8-4d77-bc6b-35bea4378c8e
=> [양가현] Feat: 포켓플레이스 인가

components/Common/CardInfo/CardSellInfo.js, components/Common/CardInfo/CardSellInfo.module.css, components/Common/CardInfo/MyCardDetail.js, components/Common/Input/Dropdown.js, components/Common/Input/Dropdown.module.css, components/Common/Modal/CardList.js, components/Common/Modal/CardList.module.css, components/Common/Modal/CardSell.js, components/Common/Modal/CardSell.module.css, components/Common/Modal/Modal.module.css, components/Common/PhotoCard/PhotoCard.module.css, lib/api/UserService.js, pages/myGallery/index.js
- CardList.js / css
- CadeSell.js / css
- Modal.module.css
- CardSellInfo.js / css
- MyCardDetail.js
- PhotoCard.module.css
- UserService.js
- 카드 리스트, 카드 판매 모달 데이터 연결
- 모달 크기 조정
- 나머지는 css 부분 살짝 여백이나 그런 정도 건드린 것 입니다.
- UserService와 index.js는 전 PR에 푸시했어야했는데 푸시하는걸 까먹어서 수정한 내용 옮긴 것 입니다.
=> [서유림] Feat: 모달수정및데이터연결

lib/api/auth.js, pages/auth/login.js, pages/auth/signup.js
추가한 파일
* login.js
* signup.js
로그인 시 엑서스토큰이 저장되고, 로그인 성공시 포켓플레이스 창으로 이동하게 변경했습니다
로그인 페이지에서 로고 클릭시 - 포켓플레이스로 이동 (추후 문의 후 수정 예정)
회원가입 페이지에서 로고 클릭시 -  랜딩페이지로 이동 (추후 문의 후 수정 예정)
하게 변경했습니다..
=> [김윤서] feat:로그인 엑서스토큰 저장

components/Common/Modal/CardList.js, lib/api/UserService.js, pages/myGallery/index.js
- UserService.js
- CardList.js
- - [x] api 수정 완료
- - [x] 해당 api 요청 부분도 수정 완료
=> [서유림] Fix: api 수정 및 관련 부분 수정

lib/api/auth.js, lib/gnb/gnb.js, lib/utils/token.js, pages/_app.js, pages/auth/login.js, pages/auth/signup.js
* 추가한 파일
lib/api/auth.js
lib/gnb/gnb.js
lib/utils/token.js
pages/auth/login.js
pages/auth/signup.js
pages/_app.js
* 변경한 내용
로그인 시 gnb가 프로필 정보를 볼 수 있게 합니다.
로그아웃 시 로그인전 gnb로 변경됩니다.
토큰 파일을 만들었습니다.
프로필 조회 api 를 추가했습니다!
코드리뷰 해주신 내용
console.log 지우기 -> 삭제했습니다
토큰 파일 만들기 -> lib/utils/token.js 파일로 만들어봤습니다 파일 위치가 맞을까요..?
시간 나실 때 확인 부탁드립니다!!
회원가입후 로그인도 가능하게 되었습니다 9ㅅ9..
=> [김윤서] Feat: 로그인 로그아웃 api 연결

lib/api/UserService.js, pages/myGallery/[id]/index.js, pages/myGallery/index.js
- UserService.js
- 마이갤러리 / 마이갤러리 상세
- - [x] api 수정 및 데이터 요청 방법 수정
=> [서유림 Fix: api 수정

pages/_app.js, pages/auth/login.js
코멘트 남겨주신 부분 삭제했습니다
로그인 후 새로고침 시 로그인이 풀리지않게 변경하였습니다.
수정한 파일
_app.js
login.js
=> [김윤서] Feat: 로그인 유지,불필요한 부분삭제

components/Common/Dropdown/Sort/Attribute.js, components/Common/Dropdown/Sort/Rating.js, components/Common/Dropdown/Sort/Sale.js, components/Common/Dropdown/Sort/Soldout.js, components/Common/Dropdown/Sort/Sort.js, components/Common/Modal/MultiFilter.js, components/Common/Modal/MultiFilter.module.css, components/PocketPlace/PocketPlaceFilter.js, components/PocketPlace/PocketPlaceFilter.module.css, components/PocketPlace/PocketPlaceList.js, components/PocketPlace/PocketPlaceList.module.css, pages/pocketPlace/index.js
- Attribute.js, Rating.js, Sale.js, Soldout.js, Sort.js
- MultiFilter.js
- MultiFilter.module.css
- PocketPlaceFilter.js
- pages/pocketPlace/index.js
- Attribute.js, Rating.js, Sale.js, Soldout.js, Sort.js: 리셋 후 원래 있던 등급, 속성 ...으로 바뀌게 코드 추가
-  MultiFilter.js: 총 개수를 보이기 위해 계산하는 함수 추가, 판매여부 -> 판매방법 수정
-  MultiFilter.module.css: 총 개수를 보이기 위해 추가
- PocketPlaceFilter.js: 필터 속성에 따라 다르게 보이기 위해 함수와 이름 수정
- PocketPlaceList.js: 여기는 대규모로 바뀌었습니다. 카드 개수별로 스크롤이 필요없게 되어서 정리했고... 멀티필터에 필요한 개수 세는 함수 추가, 쿼리스트링으로 정렬 및 필터 적용, 프론트엔드에서 해결했던 필터 코드 삭제, 등등...
-  pages/pocketPlace/index.js: filter.js와 list.js props 내려주는 코드 추가
---
너무 많은 코드가 바뀌었네요... 근데 PocketPlaceList.js는 확실히 깔끔해지긴 했습니다. ㅎㅎ 
---
https://github.com/user-attachments/assets/f883685f-91a1-416e-a774-6ac0ba94b22b
=> [양가현] Feat: 멀티필터

components/Common/Profile/Profile.js, components/Common/Profile/Profile.module.css, lib/api/auth.js, lib/gnb/gnb.js, lib/gnb/gnb.module.css
* 추가한 파일 
components/Common/Profile/Profile.js
components/Common/Profile/Profile.module.css
lib/api/auth.js
lib/gnb/gnb.js
lib/gnb/gnb.module.css
* 변경된 내용
로그인 시 gnb 상 닉네임을 눌러 프로필 모달을 확인 가능합니다!
특정 사이즈(375px) 사이즈일 경우 프로필 모달이 왼쪽 세로로 길어지며, 로그아웃 버튼이 생기게 만들었습니다!
감사합니다!
=> [김윤서] feat: 프로필 모달 기능 수정

components/Common/Input/Input.module.css, pages/auth/signup.js
* 추가한 파일
* input.css < 담당자이신 유림님에게 여쭤보고 미디어쿼리안에 비밀번호 인풋만 지웠습니다
* 회원가입 오류메세지를 출력하던것을 삭제했습니다
같은 pr로 올릴려고 했었는데.. 잘못올려서.. 따로 올리겠습니다 ㅠ
=> [김윤서] feat: 인풋 css 수정 및 회원가입 오류 수정

components/Common/CardInfo/MyCardDetail.js, components/Common/Grade/Grade.js, components/Common/PhotoCard/PhotoCard.js, components/Common/PhotoCard/PhotoCard.module.css
- PhotoCard.js / css
- Grade.js
- - [x] 교환 모달에 맞게 등급 컴포넌트 사이즈 조정
=> [서유림] Fix: grade 폰트 사이즈 수정

pages/myGallery/index.js, pages/myShop/index.js
- myShop > index.js
- - [x] 무한 스크롤 수정
- - [x] 멀티 필터 데이터 연결
- - [x] 필터 초기화 기능 구현
- 필터 때문에 뭔가 많이 복잡해지긴 했지만 기능은 잘 동작합니다. 추후 시간이 남으면 .. 좀 더 간략하게 할 수 있는 방법을 찾아보겠읍니다 ..
=> [서유림] Feat: 필터 초기화 및 모바일 필터 연결

components/Common/Modal/CardList.js, components/Common/Modal/Exchange.js, components/Common/Modal/Exchange.module.css, components/Common/Modal/MultiFilter.js
- Exchange.js
- Exchange.module.css
- MultiFilter.js
- Exchange.js : 신철님과 역할을 변경하여 신철님 파트 필터링 하였습니다!
- Exchange.module.css: 새로고침 부분 추가하여 커서 포인터 줌
- MultiFilter.js: reset을 위해 null 추가
=> [양가현] Feat: 교환하기 필터

lib/api/notifications.js
=> [김윤서] Feat:알림 api파일

components/Common/Input/Dropdown.js, components/Common/Modal/CardList.js, components/CreateCard/CreateForm.module.css
- Dropdown.js
- CreateForm.js / css
- CardList.js
- - [x] 포토 카드 생성 시 SUPER RARE 등급 서버로 전송하는 값 수정
- - [x] 포토 카드 생성 시 유효성 검사 에러 메시지 css 적용
- - [x] CardList에서 error 중복 선언으로 인한 오류 제거
=> [서유림] Feat: 포토카드 생성 등급 수정 및 에러 표출 메시지 css 수정

components/Common/Modal/AlertModals.js, components/Common/Modal/AlertModals.module.css, components/Common/Modal/CardList.js, lib/api/notifications.js, lib/gnb/gnb.js, lib/gnb/gnb.module.css
- AlertModals.js
- lib/gnb/gnb.js
- lib/gnb/gnb.module.css
- AlertModals.js : 중복 선언 삭제
- lib/gnb/gnb.js : 벨 아이콘만 클릭
- lib/gnb/gnb.module.css: 빨간 원형 알림을 위한 CSS 조정
---
https://github.com/user-attachments/assets/ed2bc867-656f-4dbd-bd6f-7e9ffcd36525
=> [양가현] Fix: 알림모달 중복 선언 수정

components/Common/Modal/CardList.js, components/Common/PhotoCard/PhotoCard.js, components/Common/PhotoCard/PhotoCard.module.css, components/MyGallery/MyGalleryList.js, components/MyGallery/MyOwnedCards.js, components/MyShop/MySaleCards.js, components/MyShop/MyShopList.js, pages/myGallery/index.js, pages/myShop/index.js
- PhotoCard.js / css
- myShop > index.js
- MyGalleryList.js
- MyShopList.js
- MyOwnedCards.js
- MySaleCards.js
- - [x] 프로필 로드 방식 변경
- - [x] 포토카드에 솔드 아웃 처리 구현
- - [x] 프로필 로드 방식 변경에 따른 해당 파일 수정
=> [서유림] Feat: 포토카드수정

components/CreateCard/CreateForm.js, components/CreateCard/CreateTitle.js, components/MyGallery/MyGalleryList.js, components/MyGallery/MyGalleryTitle.js, components/MyShop/MySaleCards.js, components/MyShop/MyShopList.js, components/MyShop/MyShopTitle.js, pages/myGallery/[id]/index.js, pages/myGallery/create.js, pages/myGallery/index.js, pages/myShop/index.js
=> [서유림] Refactor: 코드정리

components/Common/Modal/CardSell.js, components/PocketPlace/PocketPlaceList.js, lib/api/pocketPlaceAPI.js
- CardSell.js
- pocketPlaceAPI.js
- CardSell.js, pocketPlaceAPI.js : 배열 형식으로 변경
- PocketPlaceList.js : 판매 가격으로 변경
=> [양가현] Feat: 포토카드판매api

components/Common/PhotoCard/PhotoCard.js, components/Common/PhotoCard/PhotoCard.module.css
- PhotoCard.js / css
- - [x] 포토카드 컴포넌트 soldout 미디어쿼리 적용
=> [서유림] Fix: 솔드아웃 미디어 쿼리 적용

components/Common/Dropdown/Sort/Soldout.js, components/Common/Modal/AlertModals.js, components/Common/Modal/AlertModals.module.css, lib/api/notifications.js, lib/gnb/gnb.js, lib/gnb/gnb.module.css
- AlertModals.js
- AlertModals.module.css
- lib/gnb/gnb.js
- lib/api/notifications.js
- AlertModals.js : 액세스토큰 받기 위한 코드 추가
- AlertModals.module.css : 5개 이상일 때 스크롤 추가 및 읽음과 안읽음 색상 차이 구분
- lib/gnb/gnb.js : 원형 빨간색 안쪽 숫자 안읽은 숫자로 변경
- lib/api/notifications.js : 읽었을 때 true로 변환(patch)
++ 모바일 버전도 추가하였습니다.
---
https://github.com/user-attachments/assets/ffdee57e-ec81-4d95-95f5-d8e178526f31
https://github.com/user-attachments/assets/7dac7944-fc42-4fed-ae7a-e9d60f888afb
=> [양가현] Feat: 알림, 모바일 알림 추가

components/Common/Modal/CardList.js, components/Common/PhotoCard/PhotoCard.js, components/CreateCard/CreateForm.js, lib/api/UserService.js, pages/myGallery/index.js, pages/myShop/index.js
- UserService.js
- myShop > index.js
- createForm.js
- PhotoCard.js
- CardList.js
- - [x] totalCount api 추가
- - [x] 데이터 불러올 때 totalCount api 추가
- - [x] myShop 필터 구조 변경
- - [x] 포토 카드 생성 성공 / 실패 페이지 추가
- - [x] 포토카드 컴포넌트에 type 데이터 검사 추가
- - [x] 매진여부 필터링에서는 shop 올라간 것만 보이도록 수정
- - [x] CardList.js 프로필 추가
=> [서유림] Fix: 필터

components/Common/RandomBox/RandomBoxModal.js, lib/api/randomPoints.js
* 추가한 파일
랜덤포인트박스모달
랜덤포인트api 파일
랜덤포인트 뽑기 정상적으로 됩니다! 
시간부분도 연결하였습니다!
모달을 끄는 방법을 추가했습니다.
1. x 버튼을 눌러 끄기
2. 모달 밖을 눌러 끄기
=> [김윤서] Feat:랜덤 포인트 박스 api 연결

components/Common/Modal/Exchange.js, components/Common/Modal/Notification.js, components/Common/Modal/SelectCardExchange.js, components/Common/Modal/SelectCardExchange.module.css, components/Common/PhotoCard/PhotoCardExchange.js, components/Common/Quantity/QuantityCard_buyer.js, pages/card/[id]/index.js, styles/cardDetail.module.css
수정파일 
(파일체인지스 참조...)
수정내용
버튼을 요청보내고 추가로 여러번 클릭시 오류 및 여러개를 api요청하게되는 상황방지,
교환 제시 내용 없으면 오류 내용 추가
교환 제시 목록 스크롤 추가
교환시 내 카드 수량 0 이면 알림으로 수량없음 안내 추가.
=> [방신철] Feat: 페이지오류수정

components/Common/RandomBox/RandomBoxModal.module.css
=> [김윤서] Feat: 랜덤박스css 재수정

components/Common/CardInfo/MyCardDetail.js, components/Common/CardInfo/MyCardDetail.module.css
=> [서유림] Feat: 수량 없을 때 판매버튼 사라지기

pages/_app.js
=> [김윤서] Feat: 경로 변경

components/Common/Profile/Profile.module.css, lib/gnb/gnb.module.css
일단 gnb 수정먼저 했습니다 ..
알려주신 부분도 빨리 수정해보도록 하겠습니다,,
=> [김윤서] Feat: css 수정했습니다..

pages/card/[id]/index.js, styles/CardDetail.module.css
수정 파일
상세페이지 index.js /css
수정내용
이미지 크기 수정 및 pc사이즈 틀 에 맞춰 이동하게 수정
=> [방신철]상세페이지 이미지css 수정

pages/card/[id]/index.js, styles/CardDetail.module.css
=> [방신철]fix: 이미지테이블 수정

.env, pages/card/[id]/index.js, test.http
수정된 파일
상세페이지 index.js
수정내용
연관된 카드 클릭시 해당 카드상세페이지로 이동
=> [방신철]연관된 카드 클릭시 상세페이지로 이동

components/Common/Profile/Profile.module.css, components/Common/RandomBox/RandomBoxModal.js, components/Common/RandomBox/RandomBoxModal.module.css, lib/gnb/gnb.js, lib/gnb/gnb.module.css, pages/_app.js, styles/Login.module.css, styles/Signup.module.css
변경한 파일
styles/Login.module.css
styles/Signup.module.css
_app.js
gnb.module.css
gnb.js
Profile.module.css
RandomBoxModal.js
RandomBoxModal.module.css
변경 점
1. gnb바가 로그인,회원가입 페이지 위에서도 안나오게 변경했습니다 (_app.js파일)
2. 로그인, 회원가입 페이지 미디어쿼리를 개선했습니다
3. 프로필 모달을 미디어쿼리를 개선했습니다
4. gnb 바 css 수정
5. 랜덤포인트 박스모달 모바일일때 닫는아이콘이 안보이던점을 수정하고, 미디어쿼리를 개선했습니다..
6. 비로그인 상태일 때 gnb 상에 로그인 회원가입이 나오게 바꿨습니다
감사합니다 가현님 ..,
=> [김윤서] Feat: 미디어쿼리 수정

lib/gnb/gnb.js
=> [양가현] 쿠키 확인 완료로 버튼 삭제

lib/gnb/gnb.js
=> [양가현] Test: 재발급 쿠키용

lib/gnb/gnb.js
=> [양가현] Feat: 쿠키 확인용 삭제

lib/gnb/gnb.js, lib/gnb/gnb.module.css
수정한 파일명
- RandomBoxModal.module.css
- gnb.module.css
- 
---
수정한 목록 - 배포 후 피드백 받은 부분 수정했습니다.
-[x] 포인트부분, 박스이미지 커서 수정
-[x] 랜덤포인트 모달을 뽑을 수 있게 알려주는 포켓볼 좀 더 잘보이게 반짝효과 넣기
@gahyeon-yang 
사파리 로그인 문제는.. 지금까지 찾아봤지만.. 뭘 해야할지 잘 모르겠어서,, 피드백 받은 부분 수정한 부분만 올리겠습니다..
내일 더 찾아보고 수정할 수 있다면 수정하겠습니다.
내일 시간 나실 때 한번 확인 부탁 드립니다! 매번 감사합니다 가현님..
=> [김윤서] Feat: 랜덤, gnb 피드백 css수정

pages/myShop/index.js
- myShop > index.js
- 교환 완료 시 나의 판매 포토카드 리스트에서 제외되도록 설정
=> [서유림] Fix: 교환완료 시 나의 판매포토카드에서 제외

.env, components/Common/Dropdown/Sort/Attribute.js, components/Common/Dropdown/Sort/Sort.js, components/Common/Modal/AlertModals.js, components/Common/Modal/MultiFilter.js, components/Common/Modal/Notification.js, components/PocketPlace/PocketPlaceList.js, components/PocketPlace/PocketPlaceTitle.js, pages/index.js
- Sort 폴더 내  파일들: 하드코딩을 오브젝트로 만들어 리팩토링
- 알림 스크롤 제한을 해제해서 모든 알림들이 보입니다.
- 필요 없는 주석들은 삭제 했습니다
- 유틸성 함수인 Token.js를 사용하였습니다.
---
테스트 했을 때 다 잘 동작했습니다!
=> [양가현] Feat: 리팩토링

components/MyShop/MySaleCards.js
=> [서유림] Fix: super rare 값 변경
